.TH IRCIIUPD 1 "March 2013" "Doc Holliday"

.SH NAME
irciiupd \- ircIIupd, an update script for ircII

.SH DESCRIPTION
Lame update script, guy probably doesn't know how to program

.SH LICENSE
Copyright (C) 2012-2013 Doc Holliday <comment on my github>
.br 
haven't chosen a license yet

.SH BUGS
.br
- Bugs:
.UR 
https://github.com/DocHolliday/ircIIupd
.br
- Other Stuff
.UR
https://github.com/DocHolliday/ircIIupd

.SH AUTHOR
ircIIupd is written by Doc Holliday
